name: ci-fullstack-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

# Use a matrix strategy to test multiple Node.js versions
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - name: Install dependencies
        run: cd backend && npm ci

      # Run tests
      - name: Run tests
        run: cd backend && npm test

      # Run linter
      - name: Run linter
        run: cd backend && npm run lint

      # Log completion message
      - name: Completion message
        run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."
